security:
    encoders:
        Beethoven\Entity\User:
            algorithm: auto
    enable_authenticator_manager: true
    providers:
        app_user_provider:
            entity:
                class: Beethoven\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            guard:
                authenticators:
                    - Beethoven\Page\Auth\Login\LoginFormAuthenticator
            logout:
                path: frontend.auth.logout.page
                target: frontend.home.index.page

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
