services:
    Beethoven\EventListener\Topic\FilterActivePostsListener:
        tags:
            -   name: 'doctrine.orm.entity_listener'
                event: 'postLoad'
                entity: 'Beethoven\Entity\Topic'
                priority: 50

    Beethoven\EventListener\Topic\SetLastContributionListener:
        tags:
            -   name: 'doctrine.orm.entity_listener'
                event: 'postLoad'
                entity: 'Beethoven\Entity\Topic'
                priority: 40

    Beethoven\EventListener\Topic\SetLastContributionCountListener:
        tags:
            -   name: 'doctrine.orm.entity_listener'
                event: 'postLoad'
                entity: 'Beethoven\Entity\Topic'
                priority: 30

    Beethoven\EventListener\Post\FilterActiveCommentsListener:
        tags:
            -   name: 'doctrine.orm.entity_listener'
                event: 'postLoad'
                entity: 'Beethoven\Entity\Post'
                priority: 50

    Beethoven\EventListener\Post\SetLastContributionListener:
        tags:
            -   name: 'doctrine.orm.entity_listener'
                event: 'postLoad'
                entity: 'Beethoven\Entity\Post'
                priority: 40