services:
    App\EventListener\PostListener:
        tags:
            -   name: 'doctrine.orm.entity_listener'
                event: 'postLoad'
                entity: 'App\Entity\Post'

    App\EventListener\TopicListener:
        tags:
            -   name: 'doctrine.orm.entity_listener'
                event: 'postLoad'
                entity: 'App\Entity\Topic'